baseurl: '/'
permalink: pretty
title: 'Antrum Technologies'

logo:
  mobile: "images/logo/antrum-icon.svg"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/antrum-logo.svg"
  desktop_white: "images/logo/antrum-logo-white.svg"
  desktop_height: "32px"
  desktop_width: "120px"

home: 
  limit_services: 6

collections:
  support:
    output: true
    sort_by: weight
  team:
    output: true

defaults:
  - scope:
      path: ""
      type: "support"
    values:
      layout: "support-single"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
